
# Lab 3 Validation Script

# You cannot write any code in this file – to actually work on the lab, open `lab.py` and `lab.ipynb`.
#
# The only purpose of this script is to run all the public `grader.check` cells
# so that you can ensure all test cases pass using just the code in your `lab.py`.
#
# Before submitting Lab 3, run this script and make sure all test cases pass!
# If they don't, there's likely a function in `lab.ipynb` that is not implemented
# correctly in `lab.py`, or it could be that a function in `lab.py` depends on an
# object (e.g. a DataFrame) that is not an argument to that function.

# Do NOT edit this file. Instead, just call it from the command line,
# using the instructions in the assignment notebook.

import sys
questions = sys.argv[1:]


valid_ids = ['q1', 'q2', 'q3', 'q4']
break_flag = False
invalid_ids = []
for question in questions:
    if question != 'all' and question not in valid_ids:
        invalid_ids.append(question)

if len(invalid_ids) > 0:
    print(str(invalid_ids) + ' is/are not a valid question number(s). The possible question numbers are ' + str(valid_ids) + '.')
    sys.exit()

# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# %load_ext autoreload
# %autoreload 2

from lab import *

import os
import io
from pathlib import Path
import pandas as pd
import numpy as np





# do not edit this cell -- it is needed for the tests
dirname = Path('data') / 'responses'
q1_out = read_linkedin_survey(dirname)
stats_out = com_stats(q1_out)

if 'q1' in questions or questions == [] or 'all' in questions:
    print(grader.check("q1"))





# do not edit this cell -- it is needed for the tests
dirname = Path('data') / 'extra-credit-surveys'
q2_out = read_student_surveys(dirname)
check_credit_out = check_credit(q2_out)

if 'q2' in questions or questions == [] or 'all' in questions:
    print(grader.check("q2"))





# do not edit this cell -- it is needed for the tests
pets_fp = Path('data') / 'pets' / 'Pets.csv'
procedure_history_fp =  Path('data') / 'pets' / 'ProceduresHistory.csv'
owners_fp = Path('data') / 'pets' / 'Owners.csv'
procedure_detail_fp = Path('data') / 'pets' / 'ProceduresDetails.csv'
pets = pd.read_csv(pets_fp)
procedure_history = pd.read_csv(procedure_history_fp)
owners = pd.read_csv(owners_fp)
procedure_detail = pd.read_csv(procedure_detail_fp)

out_01 = most_popular_procedure(pets, procedure_history)
out_02 = pet_name_by_owner(owners, pets)
out_03 = total_cost_per_city(owners, pets, procedure_history, procedure_detail)

if 'q3' in questions or questions == [] or 'all' in questions:
    print(grader.check("q3"))





# don't change this cell -- it is needed for the tests to work
fp = Path('data') / 'sales.csv'
sales = pd.read_csv(fp)
q4_average_seller_out = average_seller(sales)
q4_product_name_out = product_name(sales)
q4_product_count_out = count_product(sales)
q4_total_by_month_out = total_by_month(sales)

if 'q4' in questions or questions == [] or 'all' in questions:
    print(grader.check("q4"))

